Add ENA taxonomy validation for samples
ebi-ait/covid-excel-utils pull request #13
Opened 2020-11-24 17:16 UTC by ke4

Changes:
- [x] Add tax ID validation
- [x] Add scientific name validation
- [x] Cross check if the given tax id and scientific name are matching

2020-11-25 10:14 UTC, MightyAx requested changes
**I would prefer the Taxonomy Validator be independent of the schema validator.**
so that cli.py CovidExcelUtils class is changed to this:
```
class CovidExcelUtils:
    docker_image = 'dockerhub.ebi.ac.uk/ait/json-schema-validator'
    validation_url = 'http://localhost:3020/validate'
    ena_url = 'https://www.ebi.ac.uk/ena/'
    
    [snip]

    def validate(self):
        try:
            with closing(DockerValidator(self.docker_image, self.validation_url)) as validator:
                self.excel.validate(validator)
        except Exception as error:
            logging.warning(f'Error validating schema, using best guess validation. Detected Error: {error}')
            self.excel.validate(ExcelValidator(self.__file_path))
        self.excel.validate(TaxonomyValidator(ena_url, self.__file_path))
```
**I would also like taxonomy_validator.py to be renamed taxonomy.py since it lives in the validation module.**

Also, please consider splitting out the the http calls to validate and handling the responses from ena into a new services/ena_taxonomy.py

2020-11-25 10:14 UTC, MightyAx commented on validation/schema.py
> +                    self.append_value(entity_errors, tax_key, error_message)
can be replaced with:
```
entity_errors.setdefault(tax_key, []).append(error_message)
```

2020-11-25 10:14 UTC, MightyAx commented on validation/schema.py
> +                    entity_errors[tax_key] = error_message
Should this be?
```
entity_errors = {tax_key: [error_message]}
```

2020-11-25 10:14 UTC, MightyAx commented on validation/schema.py
> +            dict_obj[key] = value
Can be removed by using the setdefault method of the dictionary.

2020-11-25 10:14 UTC, MightyAx commented on validation/taxonomy_validator.py
> +            errors[self.SCIENTIFIC_NAME_KEY] = "Scientific_name field is mandatory."
To match our current error format this should be:
```
if self.TAX_ID_KEY not in data_to_validate:
    errors[self.TAX_ID_KEY] = ["Tax_id field is mandatory."]
if self.SCIENTIFIC_NAME_KEY not in data_to_validate:
    errors[self.SCIENTIFIC_NAME_KEY] = ["Scientific_name field is mandatory."]
```

2020-11-25 10:14 UTC, MightyAx commented on validation/taxonomy_validator.py
> +            dict_obj[key] = [value]
Use above set default method rather than this.

2020-11-26 10:47 UTC, ke4 commented on validation/schema.py
> +                    entity_errors[tax_key] = error_message
No, the `error_message` is already a list.

2020-11-26 10:51 UTC, ke4 commented on validation/schema.py
> +                    self.append_value(entity_errors, tax_key, error_message)
I tried it, but I am afraid it is not doing the same. That's why I used that specific method.

2020-11-26 10:51 UTC, ke4 commented on validation/schema.py
> +            dict_obj[key] = value
noop, I need it

2020-11-26 11:00 UTC, MightyAx commented on validation/schema.py
> +                    self.append_value(entity_errors, tax_key, error_message)
Ah, If the error message is already a list you would need **extend**:
```
entity_errors.setdefault(tax_key, []).extend(error_message)
```

2020-11-26 11:03 UTC, MightyAx commented on validation/schema.py
> +                    entity_errors[tax_key] = error_message
so then:
`entity_errors.setdefault(tax_key, []).extend(error_message)`

2020-11-26 11:21 UTC, ke4 commented on validation/schema.py
> +                    self.append_value(entity_errors, tax_key, error_message)
`entity_errors.setdefault(tax_key,` []).extend(error_message)` it works.

2020-11-26 11:22 UTC, ke4 commented on validation/schema.py
> +            dict_obj[key] = value
Done

2020-11-26 11:22 UTC, ke4 commented on validation/schema.py
> +                    self.append_value(entity_errors, tax_key, error_message)
Done

2020-11-26 11:23 UTC, ke4 commented on validation/taxonomy_validator.py
> +            dict_obj[key] = [value]
Removed

2020-11-26 11:27 UTC, ke4 commented on validation/taxonomy_validator.py
> +            errors[self.SCIENTIFIC_NAME_KEY] = "Scientific_name field is mandatory."
No, that would break the code in `taxonomy_validation` method in `schema.py`

2020-12-08 11:24 UTC, MightyAx approved these changes

2020-12-08 14:09 UTC, ke4 reviewed
Looks fine by me

2020-12-08 14:12 UTC, merged